# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Deploy to S3
        artifacts:
          - dist/**
        script:
          - pipe: atlassian/aws-s3-deploy:0.4.1
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              S3_BUCKET: $AWS_S3_BUCKET
              LOCAL_PATH: 'dist/web-mobile'
              ACL: 'public-read'
          - pipe: atlassian/slack-notify:0.3.6
            variables:
              WEBHOOK_URL: 'https://hooks.slack.com/services/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'
              MESSAGE: 'New build available by https://s3.eu-central-1.amazonaws.com/coregames.cdn/budgeting/index.html'





