import GameModel from "../ui/game/gamemodel";

export const OperationAddition = "Addition";
export const OperationSubtraction = "Subtraction";
export const OperationDivision = "Division";
export const OperationMultiplication = "Multiplication";


export default class Config{

    constructor() {
        this.normalize();
    }



    normalize(){

        let setIndex = 0;
        let levelIndex = 0;
        let setName = "";

        this.items.forEach((item)=>{

            if(item.SetName != ""){
                setName = item.SetName;
                setIndex++;
            }else{
                item.SetName = setName;
            }

            let items = this.sets[setName];

            if(!items){
                items = [];

                this.sets[setName] = items;
            }

            item.Level = parseInt(item.Level.substring(0,1),10);



            items.push(item);

        });


    }

    sets = {};

    items = [
        {
            "SetName": "Set 1",
            "Level": "1 and up",
            "ItemType": "Takeaway Meal",
            "ItemValue": "$5",
            "Multiple": 1,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$60",
            "IncorrectAnswer1": "$40",
            "IncorrectAnswer2": "$80",
            "IncorrectAnswer3": "$50"
        },
        {
            "SetName": "",
            "Level": "1 and up",
            "ItemType": "Takeaway Meal",
            "ItemValue": "$5",
            "Multiple": 2,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$120",
            "IncorrectAnswer1": "$90",
            "IncorrectAnswer2": "$150",
            "IncorrectAnswer3": "$180"
        },
        {
            "SetName": "",
            "Level": "2 and up",
            "ItemType": "Takeaway Meal",
            "ItemValue": "$5",
            "Multiple": 3,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$180",
            "IncorrectAnswer1": "$160",
            "IncorrectAnswer2": "$120",
            "IncorrectAnswer3": "$140"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "Takeaway Meal",
            "ItemValue": "$5",
            "Multiple": 4,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$240",
            "IncorrectAnswer1": "$180",
            "IncorrectAnswer2": "$280",
            "IncorrectAnswer3": "$300"
        },
        {
            "SetName": "",
            "Level": "2 and up",
            "ItemType": "Takeaway Meal",
            "ItemValue": "$5",
            "Multiple": 1,
            "SpendTerm": "A Week",
            "SpendMultiple": 52,
            "CostTerm": "Annually",
            "Answer": "$260",
            "IncorrectAnswer1": "$280",
            "IncorrectAnswer2": "$320",
            "IncorrectAnswer3": "$350"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "Takeaway Meal",
            "ItemValue": "$5",
            "Multiple": 2,
            "SpendTerm": "A Week",
            "SpendMultiple": 52,
            "CostTerm": "Annually",
            "Answer": "$520",
            "IncorrectAnswer1": "$580",
            "IncorrectAnswer2": "$250",
            "IncorrectAnswer3": "$720"
        },
        {
            "SetName": "",
            "Level": "1 and up",
            "ItemType": "Takeaway Meal",
            "ItemValue": "$10",
            "Multiple": 1,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$120",
            "IncorrectAnswer1": "$100",
            "IncorrectAnswer2": "$140",
            "IncorrectAnswer3": "$160"
        },
        {
            "SetName": "",
            "Level": "1 and up",
            "ItemType": "Takeaway Meal",
            "ItemValue": "$10",
            "Multiple": 2,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$240",
            "IncorrectAnswer1": "$200",
            "IncorrectAnswer2": "$220",
            "IncorrectAnswer3": "$280"
        },
        {
            "SetName": "",
            "Level": "2 and up",
            "ItemType": "Takeaway Meal",
            "ItemValue": "$10",
            "Multiple": 3,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$360",
            "IncorrectAnswer1": "$300",
            "IncorrectAnswer2": "$480",
            "IncorrectAnswer3": "$420"
        },
        {
            "SetName": "",
            "Level": "2 and up",
            "ItemType": "Takeaway Meal",
            "ItemValue": "$10",
            "Multiple": 4,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$480",
            "IncorrectAnswer1": "$420",
            "IncorrectAnswer2": "$440",
            "IncorrectAnswer3": "$460"
        },
        {
            "SetName": "",
            "Level": "1 and up",
            "ItemType": "Takeaway Meal",
            "ItemValue": "$10",
            "Multiple": 1,
            "SpendTerm": "A Week",
            "SpendMultiple": 52,
            "CostTerm": "Annually",
            "Answer": "$520",
            "IncorrectAnswer1": "$550",
            "IncorrectAnswer2": "$580",
            "IncorrectAnswer3": "$480"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "Takeaway Meal",
            "ItemValue": "$10",
            "Multiple": 2,
            "SpendTerm": "A Week",
            "SpendMultiple": 52,
            "CostTerm": "Annually",
            "Answer": "$1,040",
            "IncorrectAnswer1": "$880",
            "IncorrectAnswer2": "$940",
            "IncorrectAnswer3": "$1,100"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "Takeaway Meal",
            "ItemValue": "$15",
            "Multiple": 1,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$180",
            "IncorrectAnswer1": "$200",
            "IncorrectAnswer2": "$225",
            "IncorrectAnswer3": "$125"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "Takeaway Meal",
            "ItemValue": "$15",
            "Multiple": 2,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$360",
            "IncorrectAnswer1": "$250",
            "IncorrectAnswer2": "$300",
            "IncorrectAnswer3": "$400"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "Takeaway Meal",
            "ItemValue": "$15",
            "Multiple": 1,
            "SpendTerm": "A Week",
            "SpendMultiple": 52,
            "CostTerm": "Annually",
            "Answer": "$780",
            "IncorrectAnswer1": "$575",
            "IncorrectAnswer2": "$700",
            "IncorrectAnswer3": "$680"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "Takeaway Meal",
            "ItemValue": "$15",
            "Multiple": 2,
            "SpendTerm": "A Week",
            "SpendMultiple": 52,
            "CostTerm": "Annually",
            "Answer": "$1,560",
            "IncorrectAnswer1": "$1,260",
            "IncorrectAnswer2": "$1,420",
            "IncorrectAnswer3": "$1,200"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "Takeaway Meal",
            "ItemValue": "$20",
            "Multiple": 1,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$240",
            "IncorrectAnswer1": "$420",
            "IncorrectAnswer2": "$300",
            "IncorrectAnswer3": "$380"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "Takeaway Meal",
            "ItemValue": "$20",
            "Multiple": 2,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$480",
            "IncorrectAnswer1": "$520",
            "IncorrectAnswer2": "$600",
            "IncorrectAnswer3": "$425"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "Takeaway Meal",
            "ItemValue": "$20",
            "Multiple": 1,
            "SpendTerm": "A Week",
            "SpendMultiple": 52,
            "CostTerm": "Annually",
            "Answer": "$1,040",
            "IncorrectAnswer1": "$960",
            "IncorrectAnswer2": "$1,200",
            "IncorrectAnswer3": "$1,150"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "Takeaway Meal",
            "ItemValue": "$20",
            "Multiple": 2,
            "SpendTerm": "A Week",
            "SpendMultiple": 52,
            "CostTerm": "Annually",
            "Answer": "$2,080",
            "IncorrectAnswer1": "$2,220",
            "IncorrectAnswer2": "$1,800",
            "IncorrectAnswer3": "$1,940"
        },
        {
            "SetName": "Set 2",
            "Level": "1 and up",
            "ItemType": "T-Shirt",
            "ItemValue": "$15",
            "Multiple": 2,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$30",
            "IncorrectAnswer1": "$20",
            "IncorrectAnswer2": "$45",
            "IncorrectAnswer3": "$35"
        },
        {
            "SetName": "",
            "Level": "1 and up",
            "ItemType": "T-Shirt",
            "ItemValue": "$15",
            "Multiple": 3,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$45",
            "IncorrectAnswer1": "$55",
            "IncorrectAnswer2": "$65",
            "IncorrectAnswer3": "$75"
        },
        {
            "SetName": "",
            "Level": "1 and up",
            "ItemType": "T-Shirt",
            "ItemValue": "$15",
            "Multiple": 5,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$75",
            "IncorrectAnswer1": "$55",
            "IncorrectAnswer2": "$65",
            "IncorrectAnswer3": "$85"
        },
        {
            "SetName": "",
            "Level": "2 and up",
            "ItemType": "T-Shirt",
            "ItemValue": "$15",
            "Multiple": 8,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$120",
            "IncorrectAnswer1": "$140",
            "IncorrectAnswer2": "$110",
            "IncorrectAnswer3": "$90"
        },
        {
            "SetName": "",
            "Level": "1 and up",
            "ItemType": "T-Shirt",
            "ItemValue": "$15",
            "Multiple": 1,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$180",
            "IncorrectAnswer1": "$150",
            "IncorrectAnswer2": "$210",
            "IncorrectAnswer3": "$240"
        },
        {
            "SetName": "",
            "Level": "1 and up",
            "ItemType": "T-Shirt",
            "ItemValue": "$25",
            "Multiple": 2,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$50",
            "IncorrectAnswer1": "$100",
            "IncorrectAnswer2": "$60",
            "IncorrectAnswer3": "$75"
        },
        {
            "SetName": "",
            "Level": "2 and up",
            "ItemType": "T-Shirt",
            "ItemValue": "$25",
            "Multiple": 3,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$75",
            "IncorrectAnswer1": "$85",
            "IncorrectAnswer2": "$95",
            "IncorrectAnswer3": "$65"
        },
        {
            "SetName": "",
            "Level": "2 and up",
            "ItemType": "T-Shirt",
            "ItemValue": "$25",
            "Multiple": 5,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$125",
            "IncorrectAnswer1": "$100",
            "IncorrectAnswer2": "$145",
            "IncorrectAnswer3": "$165"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "T-Shirt",
            "ItemValue": "$25",
            "Multiple": 8,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$200",
            "IncorrectAnswer1": "$160",
            "IncorrectAnswer2": "$180",
            "IncorrectAnswer3": "$220"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "T-Shirt",
            "ItemValue": "$25",
            "Multiple": 1,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$300",
            "IncorrectAnswer1": "$280",
            "IncorrectAnswer2": "$350",
            "IncorrectAnswer3": "$325"
        },
        {
            "SetName": "",
            "Level": "1 and up",
            "ItemType": "T-Shirt",
            "ItemValue": "$35",
            "Multiple": 2,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$70",
            "IncorrectAnswer1": "$60",
            "IncorrectAnswer2": "$90",
            "IncorrectAnswer3": "$110"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "T-Shirt",
            "ItemValue": "$35",
            "Multiple": 3,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$105",
            "IncorrectAnswer1": "$125",
            "IncorrectAnswer2": "$180",
            "IncorrectAnswer3": "$85"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "T-Shirt",
            "ItemValue": "$35",
            "Multiple": 5,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$175",
            "IncorrectAnswer1": "$210",
            "IncorrectAnswer2": "$145",
            "IncorrectAnswer3": "$235"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "T-Shirt",
            "ItemValue": "$35",
            "Multiple": 8,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$280",
            "IncorrectAnswer1": "$190",
            "IncorrectAnswer2": "$250",
            "IncorrectAnswer3": "$400"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "T-Shirt",
            "ItemValue": "$35",
            "Multiple": 1,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$420",
            "IncorrectAnswer1": "$350",
            "IncorrectAnswer2": "$460",
            "IncorrectAnswer3": "$585"
        },
        {
            "SetName": "",
            "Level": "1 and up",
            "ItemType": "T-Shirt",
            "ItemValue": "$45",
            "Multiple": 2,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$90",
            "IncorrectAnswer1": "$60",
            "IncorrectAnswer2": "$75",
            "IncorrectAnswer3": "$120"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "T-Shirt",
            "ItemValue": "$45",
            "Multiple": 3,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$135",
            "IncorrectAnswer1": "$90",
            "IncorrectAnswer2": "$145",
            "IncorrectAnswer3": "$175"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "T-Shirt",
            "ItemValue": "$45",
            "Multiple": 5,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$225",
            "IncorrectAnswer1": "$195",
            "IncorrectAnswer2": "$260",
            "IncorrectAnswer3": "$300"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "T-Shirt",
            "ItemValue": "$45",
            "Multiple": 8,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$360",
            "IncorrectAnswer1": "$420",
            "IncorrectAnswer2": "$500",
            "IncorrectAnswer3": "$300"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "T-Shirt",
            "ItemValue": "$45",
            "Multiple": 1,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$540",
            "IncorrectAnswer1": "$435",
            "IncorrectAnswer2": "$650",
            "IncorrectAnswer3": "$700"
        },
        {
            "SetName": "Set 3",
            "Level": "1 and up",
            "ItemType": "Sneaker",
            "ItemValue": "$50",
            "Multiple": 1,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$50",
            "IncorrectAnswer1": "$55",
            "IncorrectAnswer2": "$65",
            "IncorrectAnswer3": "$70"
        },
        {
            "SetName": "",
            "Level": "1 and up",
            "ItemType": "Sneaker",
            "ItemValue": "$50",
            "Multiple": 2,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$100",
            "IncorrectAnswer1": "$50",
            "IncorrectAnswer2": "$75",
            "IncorrectAnswer3": "$150"
        },
        {
            "SetName": "",
            "Level": "1 and up",
            "ItemType": "Sneaker",
            "ItemValue": "$50",
            "Multiple": 3,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$150",
            "IncorrectAnswer1": "$100",
            "IncorrectAnswer2": "$125",
            "IncorrectAnswer3": "$175"
        },
        {
            "SetName": "",
            "Level": "2 and up",
            "ItemType": "Sneaker",
            "ItemValue": "$50",
            "Multiple": 4,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$200",
            "IncorrectAnswer1": "$225",
            "IncorrectAnswer2": "$250",
            "IncorrectAnswer3": "$300"
        },
        {
            "SetName": "",
            "Level": "1 and up",
            "ItemType": "Sneaker",
            "ItemValue": "$75",
            "Multiple": 1,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$75",
            "IncorrectAnswer1": "$100",
            "IncorrectAnswer2": "$125",
            "IncorrectAnswer3": "$150"
        },
        {
            "SetName": "",
            "Level": "1 and up",
            "ItemType": "Sneaker",
            "ItemValue": "$75",
            "Multiple": 2,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$150",
            "IncorrectAnswer1": "$225",
            "IncorrectAnswer2": "$185",
            "IncorrectAnswer3": "$165"
        },
        {
            "SetName": "",
            "Level": "1 and up",
            "ItemType": "Sneaker",
            "ItemValue": "$75",
            "Multiple": 3,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$225",
            "IncorrectAnswer1": "$250",
            "IncorrectAnswer2": "$200",
            "IncorrectAnswer3": "$275"
        },
        {
            "SetName": "",
            "Level": "2 and up",
            "ItemType": "Sneaker",
            "ItemValue": "$75",
            "Multiple": 4,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$300",
            "IncorrectAnswer1": "$280",
            "IncorrectAnswer2": "$320",
            "IncorrectAnswer3": "$350"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "Sneaker",
            "ItemValue": "$65",
            "Multiple": 1,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$65",
            "IncorrectAnswer1": "$50",
            "IncorrectAnswer2": "$90",
            "IncorrectAnswer3": "$75"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "Sneaker",
            "ItemValue": "$65",
            "Multiple": 2,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$130",
            "IncorrectAnswer1": "$145",
            "IncorrectAnswer2": "$170",
            "IncorrectAnswer3": "$185"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "Sneaker",
            "ItemValue": "$65",
            "Multiple": 3,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$195",
            "IncorrectAnswer1": "$180",
            "IncorrectAnswer2": "$215",
            "IncorrectAnswer3": "$250"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "Sneaker",
            "ItemValue": "$65",
            "Multiple": 4,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$260",
            "IncorrectAnswer1": "$200",
            "IncorrectAnswer2": "$225",
            "IncorrectAnswer3": "$300"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "Sneaker",
            "ItemValue": "$115",
            "Multiple": 1,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$115",
            "IncorrectAnswer1": "$125",
            "IncorrectAnswer2": "$175",
            "IncorrectAnswer3": "$145"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "Sneaker",
            "ItemValue": "$115",
            "Multiple": 2,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$230",
            "IncorrectAnswer1": "$245",
            "IncorrectAnswer2": "$275",
            "IncorrectAnswer3": "$195"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "Sneaker",
            "ItemValue": "$115",
            "Multiple": 3,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$345",
            "IncorrectAnswer1": "$285",
            "IncorrectAnswer2": "$380",
            "IncorrectAnswer3": "$425"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "Sneaker",
            "ItemValue": "$115",
            "Multiple": 4,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$460",
            "IncorrectAnswer1": "$325",
            "IncorrectAnswer2": "$415",
            "IncorrectAnswer3": "$545"
        },
        {
            "SetName": "Set 4",
            "Level": "1 and up",
            "ItemType": "Haircut",
            "ItemValue": "$25",
            "Multiple": 2,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$50",
            "IncorrectAnswer1": "$25",
            "IncorrectAnswer2": "$75",
            "IncorrectAnswer3": "$100"
        },
        {
            "SetName": "",
            "Level": "1 and up",
            "ItemType": "Haircut",
            "ItemValue": "$25",
            "Multiple": 3,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$75",
            "IncorrectAnswer1": "$50",
            "IncorrectAnswer2": "$85",
            "IncorrectAnswer3": "$65"
        },
        {
            "SetName": "",
            "Level": "1 and up",
            "ItemType": "Haircut",
            "ItemValue": "$25",
            "Multiple": 4,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$100",
            "IncorrectAnswer1": "$80",
            "IncorrectAnswer2": "$120",
            "IncorrectAnswer3": "$110"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "Haircut",
            "ItemValue": "$25",
            "Multiple": 9,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$225",
            "IncorrectAnswer1": "$245",
            "IncorrectAnswer2": "$265",
            "IncorrectAnswer3": "$285"
        },
        {
            "SetName": "",
            "Level": "2 and up",
            "ItemType": "Haircut",
            "ItemValue": "$25",
            "Multiple": 1,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$300",
            "IncorrectAnswer1": "$250",
            "IncorrectAnswer2": "$280",
            "IncorrectAnswer3": "$320"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "Haircut",
            "ItemValue": "$25",
            "Multiple": 2,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$600",
            "IncorrectAnswer1": "$500",
            "IncorrectAnswer2": "$550",
            "IncorrectAnswer3": "$650"
        },
        {
            "SetName": "",
            "Level": "1 and up",
            "ItemType": "Haircut",
            "ItemValue": "$40",
            "Multiple": 2,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$80",
            "IncorrectAnswer1": "$120",
            "IncorrectAnswer2": "$100",
            "IncorrectAnswer3": "$140"
        },
        {
            "SetName": "",
            "Level": "2 and up",
            "ItemType": "Haircut",
            "ItemValue": "$40",
            "Multiple": 3,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$120",
            "IncorrectAnswer1": "$80",
            "IncorrectAnswer2": "$100",
            "IncorrectAnswer3": "$140"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "Haircut",
            "ItemValue": "$40",
            "Multiple": 4,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$160",
            "IncorrectAnswer1": "$140",
            "IncorrectAnswer2": "$180",
            "IncorrectAnswer3": "$220"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "Haircut",
            "ItemValue": "$40",
            "Multiple": 9,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$360",
            "IncorrectAnswer1": "$400",
            "IncorrectAnswer2": "$460",
            "IncorrectAnswer3": "$520"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "Haircut",
            "ItemValue": "$40",
            "Multiple": 1,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$480",
            "IncorrectAnswer1": "$400",
            "IncorrectAnswer2": "$540",
            "IncorrectAnswer3": "$620"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "Haircut",
            "ItemValue": "$40",
            "Multiple": 2,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$960",
            "IncorrectAnswer1": "$880",
            "IncorrectAnswer2": "$1,060",
            "IncorrectAnswer3": "$1,200"
        },
        {
            "SetName": "",
            "Level": "2 and up",
            "ItemType": "Haircut",
            "ItemValue": "$85",
            "Multiple": 2,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$170",
            "IncorrectAnswer1": "$150",
            "IncorrectAnswer2": "$180",
            "IncorrectAnswer3": "$160"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "Haircut",
            "ItemValue": "$85",
            "Multiple": 3,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$255",
            "IncorrectAnswer1": "$225",
            "IncorrectAnswer2": "$235",
            "IncorrectAnswer3": "$245"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "Haircut",
            "ItemValue": "$85",
            "Multiple": 4,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$340",
            "IncorrectAnswer1": "$375",
            "IncorrectAnswer2": "$425",
            "IncorrectAnswer3": "$310"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "Haircut",
            "ItemValue": "$85",
            "Multiple": 9,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$765",
            "IncorrectAnswer1": "$675",
            "IncorrectAnswer2": "$925",
            "IncorrectAnswer3": "$1,050"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "Haircut",
            "ItemValue": "$85",
            "Multiple": 1,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$1,020",
            "IncorrectAnswer1": "$880",
            "IncorrectAnswer2": "$1,200",
            "IncorrectAnswer3": "$950"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "Haircut",
            "ItemValue": "$85",
            "Multiple": 2,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$2,040",
            "IncorrectAnswer1": "$2,400",
            "IncorrectAnswer2": "$1,825",
            "IncorrectAnswer3": "$2,240"
        },
        {
            "SetName": "Set 5",
            "Level": "1 and up",
            "ItemType": "Gym Session",
            "ItemValue": "$5",
            "Multiple": 10,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$50",
            "IncorrectAnswer1": "$60",
            "IncorrectAnswer2": "$70",
            "IncorrectAnswer3": "$80"
        },
        {
            "SetName": "",
            "Level": "1 and up",
            "ItemType": "Gym Session",
            "ItemValue": "$5",
            "Multiple": 20,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$100",
            "IncorrectAnswer1": "$120",
            "IncorrectAnswer2": "$80",
            "IncorrectAnswer3": "$110"
        },
        {
            "SetName": "",
            "Level": "1 and up",
            "ItemType": "Gym Session",
            "ItemValue": "$5",
            "Multiple": 2,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$120",
            "IncorrectAnswer1": "$105",
            "IncorrectAnswer2": "$140",
            "IncorrectAnswer3": "$80"
        },
        {
            "SetName": "",
            "Level": "2 and up",
            "ItemType": "Gym Session",
            "ItemValue": "$5",
            "Multiple": 4,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$240",
            "IncorrectAnswer1": "$260",
            "IncorrectAnswer2": "$280",
            "IncorrectAnswer3": "$300"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "Gym Session",
            "ItemValue": "$5",
            "Multiple": 12,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$720",
            "IncorrectAnswer1": "$600",
            "IncorrectAnswer2": "$660",
            "IncorrectAnswer3": "$800"
        },
        {
            "SetName": "",
            "Level": "2 and up",
            "ItemType": "Gym Session",
            "ItemValue": "$5",
            "Multiple": 2,
            "SpendTerm": "A Week",
            "SpendMultiple": 52,
            "CostTerm": "Annually",
            "Answer": "$520",
            "IncorrectAnswer1": "$250",
            "IncorrectAnswer2": "$480",
            "IncorrectAnswer3": "$360"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "Gym Session",
            "ItemValue": "$5",
            "Multiple": 3,
            "SpendTerm": "A Week",
            "SpendMultiple": 52,
            "CostTerm": "Annually",
            "Answer": "$780",
            "IncorrectAnswer1": "$860",
            "IncorrectAnswer2": "$900",
            "IncorrectAnswer3": "$740"
        },
        {
            "SetName": "",
            "Level": "1 and up",
            "ItemType": "Gym Session",
            "ItemValue": "$4.50",
            "Multiple": 10,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$45",
            "IncorrectAnswer1": "$48",
            "IncorrectAnswer2": "$68",
            "IncorrectAnswer3": "$76"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "Gym Session",
            "ItemValue": "$4.50",
            "Multiple": 20,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$90",
            "IncorrectAnswer1": "$72",
            "IncorrectAnswer2": "$85",
            "IncorrectAnswer3": "$98"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "Gym Session",
            "ItemValue": "$4.50",
            "Multiple": 2,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$108",
            "IncorrectAnswer1": "$120",
            "IncorrectAnswer2": "$136",
            "IncorrectAnswer3": "$96"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "Gym Session",
            "ItemValue": "$4.50",
            "Multiple": 4,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$216",
            "IncorrectAnswer1": "$192",
            "IncorrectAnswer2": "$240",
            "IncorrectAnswer3": "$274"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "Gym Session",
            "ItemValue": "$4.50",
            "Multiple": 12,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$648",
            "IncorrectAnswer1": "$524",
            "IncorrectAnswer2": "$588",
            "IncorrectAnswer3": "$616"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "Gym Session",
            "ItemValue": "$4.50",
            "Multiple": 2,
            "SpendTerm": "A Week",
            "SpendMultiple": 52,
            "CostTerm": "Annually",
            "Answer": "$468",
            "IncorrectAnswer1": "$426",
            "IncorrectAnswer2": "$522",
            "IncorrectAnswer3": "$568"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "Gym Session",
            "ItemValue": "$4.50",
            "Multiple": 3,
            "SpendTerm": "A Week",
            "SpendMultiple": 52,
            "CostTerm": "Annually",
            "Answer": "$702",
            "IncorrectAnswer1": "$640",
            "IncorrectAnswer2": "$748",
            "IncorrectAnswer3": "$822"
        },
        {
            "SetName": "Set 6",
            "Level": "1 and up",
            "ItemType": "Shake/Smoothie",
            "ItemValue": "$5",
            "Multiple": 20,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$100",
            "IncorrectAnswer1": "$80",
            "IncorrectAnswer2": "$120",
            "IncorrectAnswer3": "$140"
        },
        {
            "SetName": "",
            "Level": "2 and up",
            "ItemType": "Shake/Smoothie",
            "ItemValue": "$5",
            "Multiple": 4,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$240",
            "IncorrectAnswer1": "$200",
            "IncorrectAnswer2": "$220",
            "IncorrectAnswer3": "$260"
        },
        {
            "SetName": "",
            "Level": "2 and up",
            "ItemType": "Shake/Smoothie",
            "ItemValue": "$5",
            "Multiple": 8,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$480",
            "IncorrectAnswer1": "$450",
            "IncorrectAnswer2": "$540",
            "IncorrectAnswer3": "$600"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "Shake/Smoothie",
            "ItemValue": "$5",
            "Multiple": 10,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$600",
            "IncorrectAnswer1": "$660",
            "IncorrectAnswer2": "$720",
            "IncorrectAnswer3": "$780"
        },
        {
            "SetName": "",
            "Level": "2 and up",
            "ItemType": "Shake/Smoothie",
            "ItemValue": "$5",
            "Multiple": 1,
            "SpendTerm": "A Week",
            "SpendMultiple": 52,
            "CostTerm": "Annually",
            "Answer": "$260",
            "IncorrectAnswer1": "$225",
            "IncorrectAnswer2": "$200",
            "IncorrectAnswer3": "$245"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "Shake/Smoothie",
            "ItemValue": "$7.50",
            "Multiple": 20,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$150",
            "IncorrectAnswer1": "$120",
            "IncorrectAnswer2": "$180",
            "IncorrectAnswer3": "$220"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "Shake/Smoothie",
            "ItemValue": "$7.50",
            "Multiple": 4,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$360",
            "IncorrectAnswer1": "$340",
            "IncorrectAnswer2": "$420",
            "IncorrectAnswer3": "$465"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "Shake/Smoothie",
            "ItemValue": "$7.50",
            "Multiple": 8,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$720",
            "IncorrectAnswer1": "$850",
            "IncorrectAnswer2": "$920",
            "IncorrectAnswer3": "$980"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "Shake/Smoothie",
            "ItemValue": "$7.50",
            "Multiple": 10,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$900",
            "IncorrectAnswer1": "$750",
            "IncorrectAnswer2": "$850",
            "IncorrectAnswer3": "$950"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "Shake/Smoothie",
            "ItemValue": "$7.50",
            "Multiple": 1,
            "SpendTerm": "A Week",
            "SpendMultiple": 52,
            "CostTerm": "Annually",
            "Answer": "$390",
            "IncorrectAnswer1": "$375",
            "IncorrectAnswer2": "$425",
            "IncorrectAnswer3": "$475"
        },
        {
            "SetName": "Set 7",
            "Level": "1 and up",
            "ItemType": "Coffee",
            "ItemValue": "$3",
            "Multiple": 100,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$300",
            "IncorrectAnswer1": "$250",
            "IncorrectAnswer2": "$350",
            "IncorrectAnswer3": "$400"
        },
        {
            "SetName": "",
            "Level": "2 and up",
            "ItemType": "Coffee",
            "ItemValue": "$3",
            "Multiple": 200,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$600",
            "IncorrectAnswer1": "$400",
            "IncorrectAnswer2": "$500",
            "IncorrectAnswer3": "$700"
        },
        {
            "SetName": "",
            "Level": "2 and up",
            "ItemType": "Coffee",
            "ItemValue": "$3",
            "Multiple": 365,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$1,095",
            "IncorrectAnswer1": "$975",
            "IncorrectAnswer2": "$1,200",
            "IncorrectAnswer3": "$1,125"
        },
        {
            "SetName": "",
            "Level": "2 and up",
            "ItemType": "Coffee",
            "ItemValue": "$3",
            "Multiple": 10,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$360",
            "IncorrectAnswer1": "$300",
            "IncorrectAnswer2": "$390",
            "IncorrectAnswer3": "$420"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "Coffee",
            "ItemValue": "$3",
            "Multiple": 15,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$540",
            "IncorrectAnswer1": "$500",
            "IncorrectAnswer2": "$575",
            "IncorrectAnswer3": "$610"
        },
        {
            "SetName": "",
            "Level": "1 and up",
            "ItemType": "Coffee",
            "ItemValue": "$3",
            "Multiple": 1,
            "SpendTerm": "A Week",
            "SpendMultiple": 52,
            "CostTerm": "Annually",
            "Answer": "$156",
            "IncorrectAnswer1": "$142",
            "IncorrectAnswer2": "$168",
            "IncorrectAnswer3": "$180"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "Coffee",
            "ItemValue": "$3",
            "Multiple": 3,
            "SpendTerm": "A Week",
            "SpendMultiple": 52,
            "CostTerm": "Annually",
            "Answer": "$468",
            "IncorrectAnswer1": "$424",
            "IncorrectAnswer2": "$496",
            "IncorrectAnswer3": "$382"
        },
        {
            "SetName": "",
            "Level": "1 and up",
            "ItemType": "Coffee",
            "ItemValue": "$4",
            "Multiple": 100,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$400",
            "IncorrectAnswer1": "$340",
            "IncorrectAnswer2": "$500",
            "IncorrectAnswer3": "$575"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "Coffee",
            "ItemValue": "$4",
            "Multiple": 200,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$800",
            "IncorrectAnswer1": "$750",
            "IncorrectAnswer2": "$850",
            "IncorrectAnswer3": "$650"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "Coffee",
            "ItemValue": "$4",
            "Multiple": 365,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$1,460",
            "IncorrectAnswer1": "$1,275",
            "IncorrectAnswer2": "$1,350",
            "IncorrectAnswer3": "$1,625"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "Coffee",
            "ItemValue": "$4",
            "Multiple": 10,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$480",
            "IncorrectAnswer1": "$400",
            "IncorrectAnswer2": "$560",
            "IncorrectAnswer3": "$620"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "Coffee",
            "ItemValue": "$4",
            "Multiple": 15,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$720",
            "IncorrectAnswer1": "$840",
            "IncorrectAnswer2": "$1,050",
            "IncorrectAnswer3": "$960"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "Coffee",
            "ItemValue": "$4",
            "Multiple": 1,
            "SpendTerm": "A Week",
            "SpendMultiple": 52,
            "CostTerm": "Annually",
            "Answer": "$208",
            "IncorrectAnswer1": "$156",
            "IncorrectAnswer2": "$182",
            "IncorrectAnswer3": "$226"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "Coffee",
            "ItemValue": "$4",
            "Multiple": 3,
            "SpendTerm": "A Week",
            "SpendMultiple": 52,
            "CostTerm": "Annually",
            "Answer": "$624",
            "IncorrectAnswer1": "$520",
            "IncorrectAnswer2": "$700",
            "IncorrectAnswer3": "$840"
        },
        {
            "SetName": "Set 8",
            "Level": "1 and up",
            "ItemType": "Slice of Cake",
            "ItemValue": "$5",
            "Multiple": 1,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$5",
            "IncorrectAnswer1": "$4",
            "IncorrectAnswer2": "$6",
            "IncorrectAnswer3": "$10"
        },
        {
            "SetName": "",
            "Level": "1 and up",
            "ItemType": "Slice of Cake",
            "ItemValue": "$5",
            "Multiple": 1,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$60",
            "IncorrectAnswer1": "$45",
            "IncorrectAnswer2": "$75",
            "IncorrectAnswer3": "$55"
        },
        {
            "SetName": "",
            "Level": "2 and up",
            "ItemType": "Slice of Cake",
            "ItemValue": "$5",
            "Multiple": 3,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$180",
            "IncorrectAnswer1": "$150",
            "IncorrectAnswer2": "$165",
            "IncorrectAnswer3": "$195"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "Slice of Cake",
            "ItemValue": "$5",
            "Multiple": 1,
            "SpendTerm": "A Week",
            "SpendMultiple": 52,
            "CostTerm": "Annually",
            "Answer": "$260",
            "IncorrectAnswer1": "$225",
            "IncorrectAnswer2": "$275",
            "IncorrectAnswer3": "$300"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "Slice of Cake",
            "ItemValue": "$5",
            "Multiple": 2,
            "SpendTerm": "A Week",
            "SpendMultiple": 52,
            "CostTerm": "Annually",
            "Answer": "$520",
            "IncorrectAnswer1": "$450",
            "IncorrectAnswer2": "$640",
            "IncorrectAnswer3": "$250"
        },
        {
            "SetName": "",
            "Level": "1 and up",
            "ItemType": "Slice of Cake",
            "ItemValue": "$6",
            "Multiple": 1,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$6",
            "IncorrectAnswer1": "$8",
            "IncorrectAnswer2": "$20",
            "IncorrectAnswer3": "$16"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "Slice of Cake",
            "ItemValue": "$6",
            "Multiple": 1,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$72",
            "IncorrectAnswer1": "$66",
            "IncorrectAnswer2": "$80",
            "IncorrectAnswer3": "$92"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "Slice of Cake",
            "ItemValue": "$6",
            "Multiple": 3,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$216",
            "IncorrectAnswer1": "$192",
            "IncorrectAnswer2": "$180",
            "IncorrectAnswer3": "$240"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "Slice of Cake",
            "ItemValue": "$6",
            "Multiple": 1,
            "SpendTerm": "A Week",
            "SpendMultiple": 52,
            "CostTerm": "Annually",
            "Answer": "$312",
            "IncorrectAnswer1": "$364",
            "IncorrectAnswer2": "$412",
            "IncorrectAnswer3": "$448"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "Slice of Cake",
            "ItemValue": "$6",
            "Multiple": 2,
            "SpendTerm": "A Week",
            "SpendMultiple": 52,
            "CostTerm": "Annually",
            "Answer": "$624",
            "IncorrectAnswer1": "$500",
            "IncorrectAnswer2": "$582",
            "IncorrectAnswer3": "$660"
        },
        {
            "SetName": "Set 9",
            "Level": "1 and up",
            "ItemType": "Milk",
            "ItemValue": "$2",
            "Multiple": 2,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$48",
            "IncorrectAnswer1": "$44",
            "IncorrectAnswer2": "$52",
            "IncorrectAnswer3": "$60"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "Milk",
            "ItemValue": "$2",
            "Multiple": 4,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$96",
            "IncorrectAnswer1": "$88",
            "IncorrectAnswer2": "$106",
            "IncorrectAnswer3": "$78"
        },
        {
            "SetName": "",
            "Level": "1 and up",
            "ItemType": "Milk",
            "ItemValue": "$2",
            "Multiple": 1,
            "SpendTerm": "A Week",
            "SpendMultiple": 52,
            "CostTerm": "Annually",
            "Answer": "$104",
            "IncorrectAnswer1": "$125",
            "IncorrectAnswer2": "$110",
            "IncorrectAnswer3": "$96"
        },
        {
            "SetName": "",
            "Level": "2 and up",
            "ItemType": "Milk",
            "ItemValue": "$2",
            "Multiple": 2,
            "SpendTerm": "A Week",
            "SpendMultiple": 52,
            "CostTerm": "Annually",
            "Answer": "$208",
            "IncorrectAnswer1": "$225",
            "IncorrectAnswer2": "$184",
            "IncorrectAnswer3": "$196"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "Milk",
            "ItemValue": "$2.50",
            "Multiple": 2,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$60",
            "IncorrectAnswer1": "$48",
            "IncorrectAnswer2": "$54",
            "IncorrectAnswer3": "$72"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "Milk",
            "ItemValue": "$2.50",
            "Multiple": 4,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$120",
            "IncorrectAnswer1": "$100",
            "IncorrectAnswer2": "$110",
            "IncorrectAnswer3": "$130"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "Milk",
            "ItemValue": "$2.50",
            "Multiple": 1,
            "SpendTerm": "A Week",
            "SpendMultiple": 52,
            "CostTerm": "Annually",
            "Answer": "$130",
            "IncorrectAnswer1": "$110",
            "IncorrectAnswer2": "$150",
            "IncorrectAnswer3": "$175"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "Milk",
            "ItemValue": "$2.50",
            "Multiple": 2,
            "SpendTerm": "A Week",
            "SpendMultiple": 52,
            "CostTerm": "Annually",
            "Answer": "$260",
            "IncorrectAnswer1": "$240",
            "IncorrectAnswer2": "$285",
            "IncorrectAnswer3": "$315"
        },
        {
            "SetName": "Set 10",
            "Level": "1 and up",
            "ItemType": "Flight",
            "ItemValue": "$200",
            "Multiple": 1,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$200",
            "IncorrectAnswer1": "$180",
            "IncorrectAnswer2": "$220",
            "IncorrectAnswer3": "$240"
        },
        {
            "SetName": "",
            "Level": "2 and up",
            "ItemType": "Flight",
            "ItemValue": "$200",
            "Multiple": 4,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$800",
            "IncorrectAnswer1": "$400",
            "IncorrectAnswer2": "$600",
            "IncorrectAnswer3": "$1,000"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "Flight",
            "ItemValue": "$200",
            "Multiple": 8,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$1,600",
            "IncorrectAnswer1": "$1,200",
            "IncorrectAnswer2": "$1,400",
            "IncorrectAnswer3": "$1,800"
        },
        {
            "SetName": "",
            "Level": "2 and up",
            "ItemType": "Flight",
            "ItemValue": "$200",
            "Multiple": 1,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$2,400",
            "IncorrectAnswer1": "$2,000",
            "IncorrectAnswer2": "$2,200",
            "IncorrectAnswer3": "$2,800"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "Flight",
            "ItemValue": "$200",
            "Multiple": 5,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$12,000",
            "IncorrectAnswer1": "$10,600",
            "IncorrectAnswer2": "$12,800",
            "IncorrectAnswer3": "$14,000"
        },
        {
            "SetName": "",
            "Level": "1 and up",
            "ItemType": "Flight",
            "ItemValue": "$250",
            "Multiple": 1,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$250",
            "IncorrectAnswer1": "$200",
            "IncorrectAnswer2": "$300",
            "IncorrectAnswer3": "$350"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "Flight",
            "ItemValue": "$250",
            "Multiple": 4,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$1,000",
            "IncorrectAnswer1": "$800",
            "IncorrectAnswer2": "$1,250",
            "IncorrectAnswer3": "$1,500"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "Flight",
            "ItemValue": "$250",
            "Multiple": 8,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$2,000",
            "IncorrectAnswer1": "$1,250",
            "IncorrectAnswer2": "$1,500",
            "IncorrectAnswer3": "$1,750"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "Flight",
            "ItemValue": "$250",
            "Multiple": 1,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$3,000",
            "IncorrectAnswer1": "$2,250",
            "IncorrectAnswer2": "$2,500",
            "IncorrectAnswer3": "$2,750"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "Flight",
            "ItemValue": "$250",
            "Multiple": 5,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$15,000",
            "IncorrectAnswer1": "$13,500",
            "IncorrectAnswer2": "$16,000",
            "IncorrectAnswer3": "$17,500"
        },
        {
            "SetName": "Set 11",
            "Level": "1 and up",
            "ItemType": "Hotel",
            "ItemValue": "$100",
            "Multiple": 1,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$100",
            "IncorrectAnswer1": "$110",
            "IncorrectAnswer2": "$120",
            "IncorrectAnswer3": "$130"
        },
        {
            "SetName": "",
            "Level": "2 and up",
            "ItemType": "Hotel",
            "ItemValue": "$100",
            "Multiple": 4,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$400",
            "IncorrectAnswer1": "$440",
            "IncorrectAnswer2": "$500",
            "IncorrectAnswer3": "$500"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "Hotel",
            "ItemValue": "$100",
            "Multiple": 10,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$1,000",
            "IncorrectAnswer1": "$1,200",
            "IncorrectAnswer2": "$1,100",
            "IncorrectAnswer3": "$900"
        },
        {
            "SetName": "",
            "Level": "1 and up",
            "ItemType": "Hotel",
            "ItemValue": "$100",
            "Multiple": 1,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$1,200",
            "IncorrectAnswer1": "$1,400",
            "IncorrectAnswer2": "$800",
            "IncorrectAnswer3": "$1,000"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "Hotel",
            "ItemValue": "$150",
            "Multiple": 1,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$150",
            "IncorrectAnswer1": "$125",
            "IncorrectAnswer2": "$175",
            "IncorrectAnswer3": "$300"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "Hotel",
            "ItemValue": "$150",
            "Multiple": 4,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$600",
            "IncorrectAnswer1": "$525",
            "IncorrectAnswer2": "$675",
            "IncorrectAnswer3": "$750"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "Hotel",
            "ItemValue": "$150",
            "Multiple": 10,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$1,500",
            "IncorrectAnswer1": "$1,000",
            "IncorrectAnswer2": "$1,225",
            "IncorrectAnswer3": "$1,400"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "Hotel",
            "ItemValue": "$150",
            "Multiple": 1,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$1,800",
            "IncorrectAnswer1": "$1,650",
            "IncorrectAnswer2": "$1,960",
            "IncorrectAnswer3": "$2,050"
        },
        {
            "SetName": "Set 12",
            "Level": "1 and up",
            "ItemType": "Gas",
            "ItemValue": "$40",
            "Multiple": 52,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$2,080",
            "IncorrectAnswer1": "$1,900",
            "IncorrectAnswer2": "$2,160",
            "IncorrectAnswer3": "$2,250"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "Gas",
            "ItemValue": "$40",
            "Multiple": 3,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$1,440",
            "IncorrectAnswer1": "$1,200",
            "IncorrectAnswer2": "$1,360",
            "IncorrectAnswer3": "$1,580"
        },
        {
            "SetName": "",
            "Level": "3 and up",
            "ItemType": "Gas",
            "ItemValue": "$40",
            "Multiple": 4,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$1,920",
            "IncorrectAnswer1": "$1,600",
            "IncorrectAnswer2": "$1,760",
            "IncorrectAnswer3": "$2,100"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "Gas",
            "ItemValue": "$40",
            "Multiple": 1,
            "SpendTerm": "A Week",
            "SpendMultiple": 52,
            "CostTerm": "Annually",
            "Answer": "$2,080",
            "IncorrectAnswer1": "$1,860",
            "IncorrectAnswer2": "$2,400",
            "IncorrectAnswer3": "$2,240"
        },
        {
            "SetName": "",
            "Level": "2 and up",
            "ItemType": "Gas",
            "ItemValue": "$40",
            "Multiple": 52,
            "SpendTerm": "A Year",
            "SpendMultiple": 1,
            "CostTerm": "Annually",
            "Answer": "$2,080",
            "IncorrectAnswer1": "$1,820",
            "IncorrectAnswer2": "$2,200",
            "IncorrectAnswer3": "$2,460"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "Gas",
            "ItemValue": "$40",
            "Multiple": 3,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$1,440",
            "IncorrectAnswer1": "$1,200",
            "IncorrectAnswer2": "$1,620",
            "IncorrectAnswer3": "$1,880"
        },
        {
            "SetName": "",
            "Level": "5 and up",
            "ItemType": "Gas",
            "ItemValue": "$40",
            "Multiple": 4,
            "SpendTerm": "A Month",
            "SpendMultiple": 12,
            "CostTerm": "Annually",
            "Answer": "$1,920",
            "IncorrectAnswer1": "$2,080",
            "IncorrectAnswer2": "$2,240",
            "IncorrectAnswer3": "$2,560"
        },
        {
            "SetName": "",
            "Level": "4 and up",
            "ItemType": "Gas",
            "ItemValue": "$40",
            "Multiple": 1,
            "SpendTerm": "A Week",
            "SpendMultiple": 52,
            "CostTerm": "Annually",
            "Answer": "$2,080",
            "IncorrectAnswer1": "$2,320",
            "IncorrectAnswer2": "$2,600",
            "IncorrectAnswer3": "$2,840"
        }
    ];

}